services:
  grafana:
    image: grafana/grafana:latest
    restart: unless-stopped
    ports:
      - '${GRAFANA_PORT}:3000'
    environment:
      GF_SECURITY_ADMIN_USER: ${GRAFANA_ADMIN_USER}
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD}
      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_AUTH_DISABLE_LOGIN_FORM: 'false'
      GF_SECURITY_ALLOW_EMBEDDING: 'true'
    volumes:
      - grafana_data:/var/lib/grafana
      - ./provisioning:/etc/grafana/provisioning:ro
    depends_on:
      - prometheus

volumes:
  grafana_data:
